# Generated by Django 3.2.8 on 2021-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211022_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
