# Generated by Django 3.2.8 on 2021-10-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211022_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day'], 'verbose_name': 'Расписание занятий', 'verbose_name_plural': 'Расписание занятий'},
        ),
    ]
